# ArivuClaw - Setup Configuration Script
# Configures .env with your API keys and starts ArivuClaw
# Run: powershell -ExecutionPolicy Bypass -File scripts\setup-config.ps1

Write-Host ""
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host "  ArivuClaw - Setup Configuration" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$arivuclawDir = Split-Path -Parent $scriptDir
Set-Location $arivuclawDir
Write-Host "  ArivuClaw directory: $arivuclawDir" -ForegroundColor Gray
Write-Host ""

# -- Check if .env already exists --
$envFile = Join-Path $arivuclawDir ".env"
$existingEnv = @{}

if (Test-Path $envFile) {
    Write-Host "  Found existing .env file. Loading current values..." -ForegroundColor Gray
    Get-Content $envFile | ForEach-Object {
        if ($_ -match "^([^#][^=]+)=(.+)$") {
            $existingEnv[$matches[1].Trim()] = $matches[2].Trim()
        }
    }
    Write-Host ""
}

# -- Helper function to prompt with default --
function Ask-Value {
    param([string]$Prompt, [string]$Key, [string]$Default)
    $current = $existingEnv[$Key]
    if ($current -and $current -ne $Default) {
        $masked = $current.Substring(0, [Math]::Min(6, $current.Length)) + "***"
        $input = Read-Host "  $Prompt (current: $masked, press Enter to keep)"
        if ([string]::IsNullOrWhiteSpace($input)) { return $current }
        return $input
    } else {
        $input = Read-Host "  $Prompt"
        if ([string]::IsNullOrWhiteSpace($input)) { return $Default }
        return $input
    }
}

# -- 1. Telegram Bot Token --
Write-Host "[1/4] Telegram Configuration" -ForegroundColor Yellow
Write-Host "  Get your bot token from @BotFather on Telegram" -ForegroundColor Gray
$telegramToken = Ask-Value -Prompt "Telegram Bot Token" -Key "TELEGRAM_BOT_TOKEN" -Default ""
if ([string]::IsNullOrWhiteSpace($telegramToken)) {
    Write-Host "  WARNING: No Telegram token - bot will not start!" -ForegroundColor Red
} else {
    Write-Host "  Telegram token set." -ForegroundColor Green
}
Write-Host ""

# -- 2. MiniMax API Key --
Write-Host "[2/4] MiniMax AI Provider" -ForegroundColor Yellow
Write-Host "  Get your API key from platform.minimaxi.com" -ForegroundColor Gray
$minimaxKey = Ask-Value -Prompt "MiniMax API Key" -Key "MINIMAX_API_KEY" -Default ""
if ([string]::IsNullOrWhiteSpace($minimaxKey)) {
    Write-Host "  WARNING: No MiniMax key - AI responses will fail!" -ForegroundColor Red
} else {
    Write-Host "  MiniMax API key set." -ForegroundColor Green
}
Write-Host ""

# -- 3. Optional: Other providers --
Write-Host "[3/4] Other API Keys (optional, press Enter to skip)" -ForegroundColor Yellow
$anthropicKey = Ask-Value -Prompt "Anthropic API Key (optional)" -Key "ANTHROPIC_API_KEY" -Default ""
$groqKey = Ask-Value -Prompt "Groq API Key (optional)" -Key "GROQ_API_KEY" -Default ""
$deepseekKey = Ask-Value -Prompt "DeepSeek API Key (optional)" -Key "DEEPSEEK_API_KEY" -Default ""
Write-Host ""

# -- 4. Write .env file --
Write-Host "[4/4] Writing .env file..." -ForegroundColor Yellow

$envContent = @"
# ArivuClaw Environment Configuration
# Generated by setup-config.ps1

# Execution Mode
ARIVUCLAW_MODE=unrestricted

# AI Provider - MiniMax
ARIVUCLAW_PROVIDER=minimax
ARIVUCLAW_MODEL=MiniMax-Text-01
MINIMAX_API_KEY=$minimaxKey

# Other Providers (optional)
ANTHROPIC_API_KEY=$anthropicKey
GROQ_API_KEY=$groqKey
DEEPSEEK_API_KEY=$deepseekKey

# Telegram Bot
TELEGRAM_BOT_TOKEN=$telegramToken

# Logging
ARIVUCLAW_LOG_LEVEL=info
"@

Set-Content -Path $envFile -Value $envContent -Encoding UTF8
Write-Host "  .env file written to: $envFile" -ForegroundColor Green
Write-Host ""

# -- Summary --
Write-Host "==============================================" -ForegroundColor Green
Write-Host "  Configuration Complete!" -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Provider:  MiniMax (MiniMax-Text-01)" -ForegroundColor White
Write-Host "  Telegram:  $(if ($telegramToken) { 'Configured' } else { 'NOT SET' })" -ForegroundColor $(if ($telegramToken) { 'Green' } else { 'Red' })
Write-Host "  Mode:      Unrestricted" -ForegroundColor White
Write-Host ""
Write-Host "  To start ArivuClaw:" -ForegroundColor White
Write-Host "    cd $arivuclawDir" -ForegroundColor Gray
Write-Host "    npx ts-node src/cli/index.ts start" -ForegroundColor Gray
Write-Host ""

# -- Ask to start now --
$startNow = Read-Host "  Start ArivuClaw now? (Y/n)"
if ($startNow -ne "n") {
    Write-Host ""
    Write-Host "  Starting ArivuClaw..." -ForegroundColor Cyan
    Write-Host ""
    npx ts-node src/cli/index.ts start
}
